name = "fabric-edge-router"
main = "src/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "fabric.cool/*", zone_name = "fabric.cool" }
]

[vars]
CF_API_URL = "https://cfapi-trougmmi5q-de.a.run.app"
CF_COMMERCE_URL = "https://cfcommerce-trougmmi5q-de.a.run.app"
FIREBASE_HOSTING_URL = "https://fabric-web-seven.vercel.app"

