name = "fabric-edge-router"
main = "src/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "fabric.cool/*", zone_name = "fabric.cool" }
]

[vars]
CF_API_URL = "https://asia-east1-fabric-production-21af4.cloudfunctions.net/cfApi"
CF_COMMERCE_URL = "https://asia-east1-fabric-production-21af4.cloudfunctions.net/cfCommerce"
FIREBASE_HOSTING_URL = "https://fabric.cool"

