apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fabric

resources:
  # Base
  - base/namespace.yaml
  - base/configmap.yaml

  # Services
  - services/gateway.yaml
  - services/order.yaml
  - services/customer.yaml
  - services/product.yaml
  - services/payment.yaml
  - services/shipping.yaml
  - services/search.yaml
  - services/promotion.yaml
  - services/notification.yaml
  - services/importer.yaml

  # Ingress
  - ingress/ingress.yaml

commonLabels:
  app.kubernetes.io/part-of:   fabric
  app.kubernetes.io/managed-by: kustomize
