import type {
  Affiliate,
  AffiliateContact,
  AffiliateEarningRow,
  AffiliateLink,
  AffiliatePayout,
  AffiliateSummaryStats,
  ContentPipelineItem,
} from "@fabric/types";

export const AFFILIATES: Affiliate[] = [
  {
    id: "aff-1",
    name: "1M Club",
    commissionRatePct: 50,
    description: "Content creation and post-scheduling tools for creators.",
    isActive: true,
    createdAt: "2023-01-01",
  },
  {
    id: "aff-2",
    name: "Late Advantage",
    commissionRatePct: 30,
    description: "Trading and business management toolkit.",
    isActive: true,
    createdAt: "2023-01-01",
  },
  {
    id: "aff-3",
    name: "Notion",
    commissionRatePct: 50,
    description: "All-in-one workspace for notes, projects, and wikis.",
    isActive: true,
    createdAt: "2023-02-01",
  },
  {
    id: "aff-4",
    name: "Typdream",
    commissionRatePct: 50,
    description: "No-code website builder for creators and entrepreneurs.",
    isActive: true,
    createdAt: "2023-02-01",
  },
  {
    id: "aff-5",
    name: "Senla",
    commissionRatePct: 50,
    description: "Email marketing and automation platform.",
    isActive: true,
    createdAt: "2023-03-01",
  },
  {
    id: "aff-6",
    name: "Hyperlay",
    commissionRatePct: 50,
    description: "Productivity suite for teams and freelancers.",
    isActive: true,
    createdAt: "2023-03-01",
  },
  {
    id: "aff-7",
    name: "Mailvite",
    commissionRatePct: 50,
    description: "Email newsletter and event invitation platform.",
    isActive: true,
    createdAt: "2023-04-01",
  },
];

export const AFFILIATE_LINKS: AffiliateLink[] = [
  {
    id: "lnk-1",
    affiliateId: "aff-1",
    platform: "youtube",
    url: "https://1mclub.io/ref/fabric",
    createdAt: "2023-01-15",
  },
  {
    id: "lnk-2",
    affiliateId: "aff-1",
    platform: "tiktok",
    url: "https://1mclub.io/ref/fabric-tt",
    createdAt: "2023-01-15",
  },
  {
    id: "lnk-3",
    affiliateId: "aff-2",
    platform: "youtube",
    url: "https://lateadvantage.com/r/fabric",
    createdAt: "2023-02-01",
  },
  {
    id: "lnk-4",
    affiliateId: "aff-2",
    platform: "instagram",
    url: "https://lateadvantage.com/r/fab-ig",
    createdAt: "2023-02-01",
  },
  {
    id: "lnk-5",
    affiliateId: "aff-3",
    platform: "youtube",
    url: "https://notion.so/fabric",
    createdAt: "2023-02-15",
  },
  {
    id: "lnk-6",
    affiliateId: "aff-4",
    platform: "tiktok",
    url: "https://typdream.com/r/fabric",
    createdAt: "2023-03-01",
  },
  {
    id: "lnk-7",
    affiliateId: "aff-5",
    platform: "youtube",
    url: "https://senla.io/ref/fabric",
    createdAt: "2023-03-15",
  },
  {
    id: "lnk-8",
    affiliateId: "aff-6",
    platform: "linkedin",
    url: "https://hyperlay.com/ref/fabric",
    createdAt: "2023-04-01",
  },
  {
    id: "lnk-9",
    affiliateId: "aff-7",
    platform: "facebook",
    url: "https://mailvite.com/r/fabric",
    createdAt: "2023-04-15",
  },
];

export const SUMMARY_STATS: AffiliateSummaryStats = {
  allTimeRevenueCents: 767_100,
  thisYearRevenueCents: 416_300,
  thisMonthRevenueCents: 63_600,
  currency: "PHP",
};

export const EARNINGS_BY_AFFILIATE: AffiliateEarningRow[] = [
  {
    affiliateId: "aff-1",
    affiliateName: "1M Club",
    commissionRatePct: 50,
    totalEarningsCents: 250_000,
    currency: "PHP",
  },
  {
    affiliateId: "aff-2",
    affiliateName: "Late Advantage",
    commissionRatePct: 30,
    totalEarningsCents: 200_000,
    currency: "PHP",
  },
  {
    affiliateId: "aff-3",
    affiliateName: "Notion",
    commissionRatePct: 50,
    totalEarningsCents: 50_000,
    currency: "PHP",
  },
  {
    affiliateId: "aff-4",
    affiliateName: "Typdream",
    commissionRatePct: 50,
    totalEarningsCents: 150_000,
    currency: "PHP",
  },
  {
    affiliateId: "aff-5",
    affiliateName: "Senla",
    commissionRatePct: 50,
    totalEarningsCents: 0,
    currency: "PHP",
  },
  {
    affiliateId: "aff-6",
    affiliateName: "Hyperlay",
    commissionRatePct: 50,
    totalEarningsCents: 0,
    currency: "PHP",
  },
  {
    affiliateId: "aff-7",
    affiliateName: "Mailvite",
    commissionRatePct: 50,
    totalEarningsCents: 0,
    currency: "PHP",
  },
];

export const PAYOUTS: (AffiliatePayout & { affiliateName: string })[] = [
  {
    id: "pay-1",
    affiliateId: "aff-1",
    affiliateName: "1M Club",
    month: "2023-09",
    amountCents: 150_000,
    currency: "PHP",
    paidAt: "2023-09-30",
  },
  {
    id: "pay-2",
    affiliateId: "aff-5",
    affiliateName: "Senla",
    month: "2023-09",
    amountCents: 92_300,
    currency: "PHP",
    paidAt: "2023-09-30",
  },
  {
    id: "pay-3",
    affiliateId: "aff-2",
    affiliateName: "Late Advantage",
    month: "2023-09",
    amountCents: 300_000,
    currency: "PHP",
    paidAt: "2023-09-30",
  },
  {
    id: "pay-4",
    affiliateId: "aff-3",
    affiliateName: "Notion",
    month: "2023-09",
    amountCents: 233_500,
    currency: "PHP",
    paidAt: "2023-09-30",
  },
  {
    id: "pay-5",
    affiliateId: "aff-5",
    affiliateName: "Senla",
    month: "2023-10",
    amountCents: 51_800,
    currency: "PHP",
    paidAt: "2023-10-31",
  },
];

export const CONTENT_PIPELINE: ContentPipelineItem[] = [
  {
    id: "c-01",
    affiliateId: "aff-1",
    title: "1M Club Review",
    platform: "youtube",
    status: "draft",
    scheduledAt: null,
    publishedAt: null,
    createdAt: "2023-10-01",
    updatedAt: "2023-10-01",
  },
  {
    id: "c-02",
    affiliateId: null,
    title: "Video Template",
    platform: "tiktok",
    status: "draft",
    scheduledAt: null,
    publishedAt: null,
    createdAt: "2023-10-02",
    updatedAt: "2023-10-02",
  },
  {
    id: "c-03",
    affiliateId: null,
    title: "Patalaz Fam by NFG",
    platform: "instagram",
    status: "draft",
    scheduledAt: null,
    publishedAt: null,
    createdAt: "2023-10-03",
    updatedAt: "2023-10-03",
  },
  {
    id: "c-04",
    affiliateId: null,
    title: "Metta Pyramid Template",
    platform: "youtube",
    status: "creating",
    scheduledAt: null,
    publishedAt: null,
    createdAt: "2023-10-04",
    updatedAt: "2023-10-05",
  },
  {
    id: "c-05",
    affiliateId: null,
    title: "Patalaz Fam by NFG",
    platform: "tiktok",
    status: "creating",
    scheduledAt: null,
    publishedAt: null,
    createdAt: "2023-10-05",
    updatedAt: "2023-10-06",
  },
  {
    id: "c-06",
    affiliateId: null,
    title: "Empty Template",
    platform: "youtube",
    status: "editing",
    scheduledAt: null,
    publishedAt: null,
    createdAt: "2023-10-01",
    updatedAt: "2023-10-07",
  },
  {
    id: "c-07",
    affiliateId: null,
    title: "Standard Template",
    platform: "tiktok",
    status: "editing",
    scheduledAt: null,
    publishedAt: null,
    createdAt: "2023-10-01",
    updatedAt: "2023-10-07",
  },
  {
    id: "c-08",
    affiliateId: null,
    title: "Metta Pyramid Template",
    platform: "instagram",
    status: "editing",
    scheduledAt: null,
    publishedAt: null,
    createdAt: "2023-10-04",
    updatedAt: "2023-10-08",
  },
  {
    id: "c-09",
    affiliateId: "aff-4",
    title: "Typdream Walkthrough",
    platform: "youtube",
    status: "editing",
    scheduledAt: null,
    publishedAt: null,
    createdAt: "2023-10-06",
    updatedAt: "2023-10-09",
  },
  {
    id: "c-10",
    affiliateId: null,
    title: "Standard Template",
    platform: "youtube",
    status: "ready_to_post",
    scheduledAt: "2023-11-01",
    publishedAt: null,
    createdAt: "2023-10-01",
    updatedAt: "2023-10-10",
  },
  {
    id: "c-11",
    affiliateId: "aff-2",
    title: "Late Advantage Tutorial",
    platform: "youtube",
    status: "ready_to_post",
    scheduledAt: "2023-11-03",
    publishedAt: null,
    createdAt: "2023-10-02",
    updatedAt: "2023-10-10",
  },
  {
    id: "c-12",
    affiliateId: null,
    title: "Patalaz Fam by NFG",
    platform: "facebook",
    status: "ready_to_post",
    scheduledAt: "2023-11-05",
    publishedAt: null,
    createdAt: "2023-10-03",
    updatedAt: "2023-10-11",
  },
  {
    id: "c-13",
    affiliateId: "aff-5",
    title: "Senla Email Marketing Tips",
    platform: "linkedin",
    status: "ready_to_post",
    scheduledAt: "2023-11-06",
    publishedAt: null,
    createdAt: "2023-10-04",
    updatedAt: "2023-10-11",
  },
  {
    id: "c-14",
    affiliateId: "aff-1",
    title: "1M Club Unboxing",
    platform: "youtube",
    status: "published",
    scheduledAt: null,
    publishedAt: "2023-09-15",
    createdAt: "2023-09-01",
    updatedAt: "2023-09-15",
  },
  {
    id: "c-15",
    affiliateId: "aff-3",
    title: "Notion for Creators",
    platform: "tiktok",
    status: "published",
    scheduledAt: null,
    publishedAt: "2023-09-20",
    createdAt: "2023-09-05",
    updatedAt: "2023-09-20",
  },
  {
    id: "c-16",
    affiliateId: "aff-2",
    title: "Late Advantage: 30d Results",
    platform: "youtube",
    status: "published",
    scheduledAt: null,
    publishedAt: "2023-10-01",
    createdAt: "2023-09-10",
    updatedAt: "2023-10-01",
  },
];

export const CONTACTS: AffiliateContact[] = [
  {
    id: "con-1",
    affiliateId: "aff-1",
    name: "Aacxilia",
    email: "aacxilia@example.com",
    status: "contacted",
    notes: "Interested in 1M Club co-promo",
    createdAt: "2023-09-01",
  },
  {
    id: "con-2",
    affiliateId: "aff-2",
    name: "Atiyah",
    email: "atiyah@example.com",
    status: "responded",
    notes: "Awaiting content brief approval",
    createdAt: "2023-09-05",
  },
  {
    id: "con-3",
    affiliateId: "aff-3",
    name: "Gonzales Isabella",
    email: "isabella@example.com",
    status: "contacted",
    notes: "Notion campus ambassador lead",
    createdAt: "2023-09-08",
  },
  {
    id: "con-4",
    affiliateId: "aff-5",
    name: "Kikoro Vince",
    email: "vince@example.com",
    status: "converted",
    notes: "Signed Senla partnership deal",
    createdAt: "2023-08-20",
  },
  {
    id: "con-5",
    affiliateId: "aff-4",
    name: "Reyes Lucas",
    email: "lucas@example.com",
    status: "pending",
    notes: null,
    createdAt: "2023-10-01",
  },
  {
    id: "con-6",
    affiliateId: "aff-4",
    name: "Reyes Sofia",
    email: "sofia@example.com",
    status: "contacted",
    notes: "Typdream brand fit review",
    createdAt: "2023-10-02",
  },
];

export function formatPhpCents(cents: number): string {
  return `₱${(cents / 100).toLocaleString("en-US", { minimumFractionDigits: 0, maximumFractionDigits: 0 })}`;
}
